name: Run Linters
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'webclient/.nvmrc'
      - run: |
          cd webclient
          npm ci
      - uses: sibiraj-s/action-eslint@v2
          with:
            fail_on_error: true
            workdir: webclient   